---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-account
  namespace: loch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-admin
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: namespace-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
  - kind: ServiceAccount
    name: namespace-account
    namespace: loch

---
apiVersion: batch/v1
kind: Job
metadata:
  name: clean
  namespace: loch
spec:
  template:
    metadata:
      name: clean
    spec:
      serviceAccountName: namespace-account
      containers:
        - name: clean
          image: clean:v0.1.0
          command:
            - "/opt/clean"
      restartPolicy: OnFailure

# ---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: clean
#   namespace: loch
# spec:
#   schedule: "*/120 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           serviceAccountName: namespace-account
#           containers:
#             - name: clean
#               image: clean:v0.1.0
#               command:
#                 - "/opt/clean"
#           restartPolicy: OnFailure